### PR TITLE
Add information about how the build works

### PR DESCRIPTION
**Pull request by iainduncani**
This change is [Reviewable](https://reviewable.io/reviews/gameontext/sample-room-java/46)

### CODE REVIEW

**Comment by katheris** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 110 at r1](https://reviewable.io:443/reviews/gameontext/sample-room-java/46#-KZfbTj7Uvf0d3E9Zq6i:-KZfbTj7Uvf0d3E9Zq6j:b-chgn87) ([raw file](https://github.com/gameontext/sample-room-java/blob/d36abf9480bea50c233d12d154cb9b4199c5787f/README.md#L110)):*
> ```Markdown
> ### Testing
> 
> You can write two types of tests: unit and integration tests.  The unit tests will use the maven-surefire-plugin to run any tests found in packages that include "unit" in their name. The integration tests will start a Liberty server before using the maven-failsafe-plugin to run any tests with in pacakges that include "it" in their names before then stopping the Liberty server. As integration tests are longer running then can be skipped by providing the skipTests flag: `mvn install -DskipTests`.
> ```

Spelling mistake of packages, and doesn't quite make sense. Also then->they

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/sample-room-java/46)*

**Comment by iainduncani** [comment]
*[README.md, line 110 at r1](https://reviewable.io:443/reviews/gameontext/sample-room-java/46#-KZfbTj7Uvf0d3E9Zq6i:-KZfnqIKT3pOrYayi8lV:b-2v8kni) ([raw file](https://github.com/gameontext/sample-room-java/blob/d36abf9480bea50c233d12d154cb9b4199c5787f/README.md#L110)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

Spelling mistake of packages, and doesn't quite make sense. Also then->they
</blockquote></details>

I've fixed the typos. I wasn't sure which part didn't make sense so I made it a list in an effort to make it clearer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/sample-room-java/46)*

**Comment by katheris** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 113 at r2](https://reviewable.io:443/reviews/gameontext/sample-room-java/46#-KZfsPyrdyRgkvXlzwYf:-KZfsPysh6kDhbdyFH6y:b-mi68ul) ([raw file](https://github.com/gameontext/sample-room-java/blob/3f2b4c0814592031160fcb9687581c06e27afd3d/README.md#L113)):*
> ```Markdown
> 1. Start a Liberty server
> 2. Use the maven-failsafe-plugin to run any tests with in packages that include "it" in their names
> 3. Stop the Liberty server
> ```

Number 2 should say:
2. Use the maven-failsafe-plugin to run any tests that have packages that include "it" in their names

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/sample-room-java/46)*

**Comment by katheris** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/sample-room-java/46)*

**Comment by iainduncani** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 113 at r2](https://reviewable.io:443/reviews/gameontext/sample-room-java/46#-KZfsPyrdyRgkvXlzwYf:-K_c2OWPgNMbaYzggVdd:b-896fix) ([raw file](https://github.com/gameontext/sample-room-java/blob/3f2b4c0814592031160fcb9687581c06e27afd3d/README.md#L113)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary><blockquote>

Number 2 should say:
2. Use the maven-failsafe-plugin to run any tests that have packages that include "it" in their names
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/sample-room-java/46)*

**Comment by katheris** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/sample-room-java/46)*

**Pull request merged**
